
#=========================================================================
#
#   Program to generate realized random numbers from the
#       1. Time invariant model
#       2. Count model
#       3. Linear regression model
#       4. Exponential regression model
#       5. Autoregressive model
#       6. Bilinear model
#       7. Autoregressive and heteroskedastic model
#       8. ARCH model
#    
#   The realizations of the random draws from the models will be 
#   different to those reported in the text as the random numbers
#   generated by the Gauss random number generator differ from those 
#   generated by Matlab. Consequently the realizations are not printed
#   in this program and the PICTURE WILL BE DIFFERENT TO THE FIGURES
#   IN CHAPTER 1.
#
#=========================================================================

rm(list = ls(all = TRUE))
graphics.off()

# load required functions - figure
source("EMTSUtil.R")
# load library - repmat, zeros
library('matlab')

# Set seed of random number generator
set.seed(1234567)

t <- 5       

# Time invariant model

mu  <- 0                            # Mean
sig <- 2                            # Standard deviation                           
z   <- rnorm(t)                  # Standard normal random numbers     
y   <- sig*z                        # Generate realizations of y                      
s   <- seq(from=-10, by=0.1, to=10)                  
fz  <- dnorm(s)                   # Probability distribution of z       
fy  <- dnorm((s-mu)/sig)*(1/sig)  # Probability distribution of y                   
s1  <- s  
y1  <- y 
fz1 <- fz
fy1 <- fy

# Count model
theta   <- 2                                 
y       <- rpois(t, theta)                                            
s       <- seq(from=0, to=9, by=1)                       
s2      <- s
y2      <- y
fy2     <- dpois(s,theta)

# Linear regression model
beta <- 3                                       
sig  <- 2
z    <- rnorm(t)                              
x    <- seq(from=0, by=1, to=t-1)                              
y    <- beta*x + sig*z                          
s    <- seq(from=-10, by=0.1, to=20)                        
fz   <- dnorm(s)                              
tmp0 <- repmat(s,1,length(x))
tmp1 <- repmat(beta*x,length(s),1)
fy   <- dnorm( (tmp0-tmp1)/sig )*(1/sig)     
s3   <- s                                        
y3   <- y
fz3  <- fz
fy3  <- fy


# Exponential regression model
b0    <- 1                             
b1    <- 2
x     <- seq(from=0, by=1, to=t-1)                  
mu    <- b0 + b1*x
z    <- runif(t)                     
y    <- -mu*log(1 - z)               
s    <- seq(from=0.1, by=0.1, to=20)                
tmp0 <- repmat( s,1,length(mu) )
tmp1 <- repmat( mu,length(s),1 )
fy   <- exp(-tmp0/tmp1)/tmp1        
s4   <- s
y4   <- y
fy4  <- fy

# Autoregressive model
rho <- 0.8                                                             
sig <- 2
u   <- sig*rnorm(t+1)                       

y0 <- 0
for (i in 2:length(u+1))   {
  y0[i] <- rho*y0[i-1]+u[i-1]
}


y    <- y0[-1]
yl   <- y0[-length(y0)]                                                    
s    <- seq(from=-10, by=0.1, to=10)  
fu   <- dnorm(s/sig)*(1/sig)              
tmp0 <- repmat(s,1,length(rho*yl))
tmp1 <- repmat(rho*yl,length(s),1)
fu   <- dnorm(s/sig)*(1/sig)              
tmp1 <- repmat(rho*yl,length(s),1)
fy   <- dnorm( (tmp0-tmp1)/sig )*(1/sig)
s5   <- s
y5   <- y
fu5  <- fu
fy5  <- fy


# Bilinear time series model
rho <- 0.8                                                            
gam <- 0.4
sig <- 2

u  <- sig*rnorm(t)                       
mu <- zeros(t,1)
y  <- zeros(t,1)


for (i in 2:t) {
  mu[i] <- rho*y[i-1] + gam*y[i-1]*u[i-1]
  y[i]  <- mu[i] + u[i]
}
s  <- seq(from=-10, by=0.1, to=10)                      	

fu <- dnorm(s/sig)*(1/sig)                               

tmp0 <- repmat(s,1,length(mu))
tmp1 <- repmat(mu,length(s),1)
fy   <- dnorm( (tmp0-tmp1)/sig )*(1/sig)  
               
s6 <- s
y6 <- y
fu6 <- fu
fy6 <- fy

# Autoregressive model with heteroskedasticity
rho <- 0.8                                                                
a0  <- 0.8
a1  <- 0.8

w    <- runif(t+1)                             
sig2 <- a0 + a1*w                                                   
sig  <- sqrt(sig2)                              

u <- sig*runif(t+1)                           

y0 <- 0.0
for (i in 2:length(u+1)) {
  y0[i] <- rho*y0[i-1]+u[i-1]
}   
y   <- y0[-1]
yl  <- y0[-length(y0)]                                                        
sig <- sig[-1]
               
s  <- seq(from=-10, by=0.1, to=10)                                 

fz <- dnorm(s)                                             

tmp0 <- repmat(s,1,length(rho*yl))
tmp1 <- repmat(rho*yl,length(s),1)
tmp2 <- repmat(sig,length(s),1)
fu   <- dnorm(tmp0/tmp2)*(1/tmp2)           
fy   <- dnorm( (tmp0-tmp1)/tmp2 )*(1/tmp2) 

s7   <- s
y7   <- y
fz7  <- fz
fy7  <- fy


# ARCH model
beta   <- 3.0                                                 
alpha0 <- 4.0
alpha1 <- 0.9

z <- rnorm(t+1)                            
x <- seq(from=-1, by=1, to=t-1)                           	            
y0 <- zeros(t,1)
u <- zeros(t+1,1)
sig2 <- zeros(t+1,1) + alpha0
sig <- sqrt(sig2)

for (i in 2:t) {
  sig2[i] <- alpha0 + alpha1*u[i-1]^2
  sig[i]  <- sqrt(sig2[i])
  u[i]    <- sig[i]*z[i]
  y0[i]   <- beta*x[i] + u[i]
}


y   <- y0[-1]
x   <- x[-1]
sig <- sig[-1]

s <- seq(from=-10, by=0.1, to=20)                     	     
fz <- dnorm(s)                                           
tmp0 <- repmat(s,1,length(beta*x))
tmp1 <- repmat(beta*x,length(s),1)
tmp2 <- repmat(sig,length(s),1)
fy <- dnorm((tmp0-tmp1)/tmp2 )*(1/tmp2) 	                 
               
s8 <- s
y8 <- y
fz8 <- fz
fy8 <- fy

# Plot the data


figure()
par(mfrow=c(4,2))

#--------------------------------------------------------#
# Panel (a)
matplot(s1,cbind(fz1,fy1), type = 'l', 
        main = '(a) Time Invariant Model',
        ylab = expression(f(y)), 
        xlab = 'y',
        lty = 1:2,
        col = c("red", "blue"),
        bty = 'l')
legend("topright", c("z", "y"),
       lty=1:2, col = c("red", "blue"))


#--------------------------------------------------------#
# Panel (b)
barplot(fy2, 
        main = '(b) Count Model',
        ylab = expression(f(y)),
        xlab = expression(y))



#--------------------------------------------------------#
# Panel (c)
matplot(s3,cbind(fy3[,1],fy3[,3],fy3[,5]), type = 'l',
        main = '(c) Linear Regression Model',
        ylab = expression(f(y)),
        xlab = expression(y),
        bty = 'l')

#--------------------------------------------------------#
# Panel (d)
s4 <- seq(from=0.1, by=0.1, to=20)
matplot(s4,cbind(fy4[,1], fy4[,3],fy4[,5]), type = 'l',
        main = '(d) Exponential Regression Model',
        ylab = expression(f(y)),
        xlab = expression(y),
        bty = 'l')

#--------------------------------------------------------#
# Panel (e)
matplot(s5,cbind(fy5[,1],fy5[,3],fy5[,5]), type = 'l',
        main = '(a) Autoregressive Model', 
        ylab = expression(f(y)),
        xlab = expression(y),
        bty = 'l')


#--------------------------------------------------------#
# Panel (f)
matplot(s6,cbind(fy6[,1],fy6[,3],fy6[,5]), type = 'l',
        main = '(b) Bilinear Model',
        ylab = expression(f(y)),
        xlab = expression(y),
        bty = 'l')

#--------------------------------------------------------#
# Panel (g)
matplot(s7,cbind(fy7[,1],fy7[,3],fy7[,5]), type = 'l',
        main = '(c) Autoregressive Heteroskedastic Model',
        ylab = expression(f(y)),
        xlab = expression(y),
        bty = 'l')


#--------------------------------------------------------#
# Panel (d)

matplot(s8,cbind(fy8[,1],fy8[,3],fy8[,5]), type='l',
        main = '(d) ARCH Model',
        ylab = expression (f(y)),
        xlab = expression(y),
        bty = 'l')
